# Generated by Django 5.2.6 on 2025-09-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.CharField(max_length=10)),
                ('contenido', models.JSONField()),
                ('Fecha_Creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_Actualizacion', models.DateTimeField(auto_now=True)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
            options={
                'ordering': ['-Fecha_Creacion'],
                'unique_together': {('Proyecto', 'Version')},
            },
        ),
    ]
